# Nuclio Debugger

name: CI Nuclio

on:
  push:
    branches: [ main ]

env:
  CONTAINER_NAME: cvat/ultralytics-yolov5

jobs:
  nuclio-container:
    name: Nulcio Container
    runs-on: ubuntu-latest
    container:
      image: quay.io/nuclio/dashboard:1.5.16-amd64
      volumes:
        - /tmp:/tmp
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        no_proxy: 172.28.0.1,${no_proxy}
        NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
        NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
      ports:
        - '8070:8070'
    steps:
      - name: Success Running
        run: echo "🎉 Nuclio Container Success Running."

  deploy-model:
    needs: [ nuclio-container ]
    name: Deploy Model 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Deploy Model
        run: ./deploy.sh ./yolov5

      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v1